name: flutter_mobile_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  cloudinary_flutter: ^1.0.0
  cloudinary_url_gen: ^1.0.0
  cached_network_image: ^3.2.3
  flutter_secure_storage: ^6.0.0

  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
